# Model configurations for Agent Performance Evaluator

[gpt-4o]
model_id = "gpt-4o"
api_key = ""
base_url = ""

[gpt-4o-mini]
model_id = "gpt-4o-mini"
api_key = ""
base_url = ""

[claude-3-5-sonnet]
model_id = "claude-3-5-sonnet-20241022"
api_key = ""
base_url = ""

[claude-3-7-sonnet]
model_id = "claude-3-7-sonnet-20240229"
api_key = ""
base_url = ""

[deepseek-v3-0324]
model_id = "deepseek-v3-0324"
api_key = ""
base_url = ""

[qwen2-5-7b]
model_id = "Qwen2-5-7b"
api_key = ""
base_url = ""

[qwen2-5-14b]
model_id = "Qwen2-5-14b"
api_key = ""
base_url = ""

[qwen2-5-72b]
model_id = "Qwen2-5-72b"
api_key = ""
base_url = ""