def waste_calculation_calculate(population, location):
	"""
	Calculates the estimated waste generated by different population sizes in a specific location.    
	Parameters:
	population: The description of population. 'adults' is the number of adults in the household. 'children' is the number of children. 'singles' is the number of single adults living alone.
	location: The city where the population resides.

	"""
	pass

tools = [waste_calculation_calculate]
